"""
analytics_report.py

THE FINAL, SINGLE FILE the underwriter actually opens.

Everything else we built (unified_claims.json, risk_metrics.json,
underwriting_memo.md) is machine-friendly output. This script combines
all three into ONE human-readable report, in Markdown, mixing tables
(for scanning numbers fast) with short text sections (for context) -
built for someone who wants the full risk picture in under 2 minutes
of reading.

IMPORTANT DESIGN CHOICE: every table below is built with plain Python
string formatting, reading directly from risk_metrics.json /
unified_claims.json - NOT generated by an LLM. Those numbers were
already computed correctly in Step 6; there's no reason to let an LLM
re-type them and risk a transcription error in the one document the
underwriter actually trusts. The LLM's job (memo.py, Step 7) stays
narrative-only, and its output is folded in as a section, not
regenerated here.

Orchestration note: this file makes no LLM calls at all, so there's no
Agent to swap in here (unlike structuring.py/memo.py) - "using Andromeda"
for a pure-formatting step means wiring it through the same
WorkflowBuilder shape the other steps use, so it plugs into one pipeline
later instead of being a disconnected fourth script. No other logic
changed.
"""

import json
import os

import scoring   # reuses the same OUTPUT_PATH / file locations
import memo       # reuses MEMO_OUT location

from andromeda.core.workflow import WorkflowBuilder


ANALYTICS_REPORT_OUT = os.path.join(scoring.OUTPUT_PATH, "analytics_report.md")


def pct(value):
    return f"{value}%" if value is not None else "N/A"


def money(value):
    return f"${value:,.2f}" if value is not None else "N/A"


def build_kpi_dashboard(summary: dict, aggregate: dict, open_exposure: dict, large_losses: list) -> str:
    """Top-of-report 'glance table' - the handful of numbers an underwriter checks first."""
    rows = [
        ("Insured", summary["insured_name"]),
        ("Policy years covered", summary["policy_years_covered"]),
        ("Total claims (all years)", summary["total_claims"]),
        ("Total premium (all years)", money(summary["total_premium_all_years"])),
        ("Total incurred (all years)", money(aggregate["total_incurred"])),
        ("Overall loss ratio", pct(aggregate["overall_loss_ratio_pct"])),
        ("Avg claims per year", aggregate["avg_claims_per_year"]),
        ("Open exposure (outstanding reserves)", money(open_exposure["total_outstanding_reserve"])),
        ("Open claims", open_exposure["open_claim_count"]),
        ("Large losses flagged (≥50% of limit)", len(large_losses)),
    ]
    lines = ["| KPI | Value |", "|---|---|"]
    for label, value in rows:
        lines.append(f"| {label} | {value} |")
    return "\n".join(lines)


def build_year_over_year_table(by_year: dict) -> str:
    """
    The core underwriting table: one row per prior policy year, showing
    whether each year was profitable for the PRIOR carrier (loss ratio
    < 100% = the carrier collected more than it paid out; >= 100% = the
    carrier lost money on this account that year).
    """
    lines = [
        "| Policy Year | Carrier | Premium | Total Incurred | Loss Ratio | Claims | Open % | Prior Carrier Profitable? |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for year_label, m in by_year.items():
        loss_ratio = m["loss_ratio_pct"]
        profitable = "N/A" if loss_ratio is None else ("Yes" if loss_ratio < 100 else "No")
        lines.append(
            f"| {year_label} | {m['carrier_name'] or 'Unknown'} | {money(m['premium'])} | "
            f"{money(m['total_incurred'])} | {pct(loss_ratio)} | {m['claim_count']} | "
            f"{pct(m['pct_claims_open'])} | {profitable} |"
        )
    return "\n".join(lines)


def build_cause_of_loss_table(top_causes: list, total_claims: int) -> str:
    """What TYPES of claims are happening, and how often - operational hazard signal."""
    lines = ["| Cause of Loss | Count | % of All Claims |", "|---|---|---|"]
    for entry in top_causes:
        share = round((entry["count"] / total_claims) * 100, 1) if total_claims else 0
        lines.append(f"| {entry['cause']} | {entry['count']} | {share}% |")
    return "\n".join(lines)


def build_large_losses_table(large_losses: list) -> str:
    if not large_losses:
        return "_No individual claims exceeded 50% of the per-occurrence limit._"
    lines = ["| Claim # | Policy Year | Total Incurred | % of Per-Occ Limit |", "|---|---|---|---|"]
    for c in large_losses:
        lines.append(
            f"| {c['claim_number']} | {c['policy_year']} | {money(c['total_incurred'])} | "
            f"{pct(c['pct_of_limit'])} |"
        )
    return "\n".join(lines)


def build_trend_section(trend: dict | None) -> str:
    if not trend:
        return "_Not enough policy years with valid data to compute a trend._"
    arrow = "↑ worsening" if trend["direction"] == "worsening" else \
            "↓ improving" if trend["direction"] == "improving" else "→ flat"
    return (
        f"**Direction: {arrow}**\n\n"
        f"- Oldest year ({trend['oldest_year']}): {pct(trend['oldest_year_loss_ratio_pct'])} loss ratio\n"
        f"- Newest year ({trend['newest_year']}): {pct(trend['newest_year_loss_ratio_pct'])} loss ratio"
    )


def build_maturity_caveats_section(caveats: list) -> str:
    if not caveats:
        return "_No significant maturity concerns - claims data appears reasonably settled._"
    return "\n".join(f"- ⚠ {c}" for c in caveats)


def extract_executive_summary(memo_text: str) -> str:
    """Pulls just the Executive Summary section out of the LLM memo, so we
    don't duplicate the entire memo inside this report - just the top-line
    narrative, with a pointer to the full memo file for more detail."""
    if "## Executive Summary" not in memo_text:
        return memo_text[:400]  # fallback: just take the top of whatever came back
    after = memo_text.split("## Executive Summary", 1)[1]
    # stop at the next "## " heading, if there is one
    next_heading = after.find("\n## ")
    return after[:next_heading].strip() if next_heading != -1 else after.strip()


def step_report(state: dict) -> dict:
    with open(scoring.UNIFIED_CLAIMS_OUT, "r") as f:
        unified = json.load(f)
    with open(scoring.RISK_METRICS_OUT, "r") as f:
        m = json.load(f)

    summary = unified["submission_summary"]

    exec_summary = "_Run memo.py first to generate the narrative executive summary._"
    if os.path.exists(memo.MEMO_OUT):
        with open(memo.MEMO_OUT, "r") as f:
            exec_summary = extract_executive_summary(f.read())

    report = f"""# Underwriting Risk Analytics Report
### {summary['insured_name']}

---

## Executive Summary
{exec_summary}

---

## KPI Dashboard

{build_kpi_dashboard(summary, m['aggregate'], m['open_exposure'], m['large_losses'])}

---

## Loss Experience by Policy Year

{build_year_over_year_table(m['by_policy_year'])}

*"Prior Carrier Profitable?" = Yes when that year's loss ratio was under 100% (the carrier \
collected more in premium than it paid out); No when the carrier likely lost money on this \
account that year.*

---

## Trend

{build_trend_section(m['trend'])}

---

## Cause of Loss Breakdown

{build_cause_of_loss_table(m['top_causes_of_loss'], summary['total_claims'])}

---

## Notable Large Losses

{build_large_losses_table(m['large_losses'])}

---

## Data Maturity & Caveats

{build_maturity_caveats_section(m['maturity_caveats'])}

---

*Full narrative memo: `{os.path.basename(memo.MEMO_OUT)}` | Full claims table: \
`{os.path.basename(scoring.UNIFIED_CLAIMS_OUT)}` | Full metrics: \
`{os.path.basename(scoring.RISK_METRICS_OUT)}`*
"""

    with open(ANALYTICS_REPORT_OUT, "w") as f:
        f.write(report)

    print(f"Analytics report saved to: {ANALYTICS_REPORT_OUT}")
    return {"report_text": report, "report_path": ANALYTICS_REPORT_OUT}


def build_report_pipeline() -> WorkflowBuilder:
    pipeline = WorkflowBuilder(name="AnalyticsReportPipeline")
    pipeline.start("report").run(step_report)
    return pipeline


def build_report():
    pipeline = build_report_pipeline()
    result = pipeline.execute(state={})
    return result["report_text"]


if __name__ == "__main__":
    build_report()
